### PR TITLE
[Migrate CI] Added workflow for GitHub actions CI. Deleted travis.yml.

### LINKED ISSUE #1314: Enable CI with GitHub actions for the SODA API
**Issue/Feature Description:**
The current CI across SODA Projects is being run using Travis CI. With the changes made to the free tier of Travis CI we are moving the CI for all the projects under SODA Foundation to GitHub Actions.
As part of this we need to move the CI for the API project to GitHub Actions

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
Currently the CI jobs are getting queued across the SODA Organisation and this is causing delays in the CI's being run if there are many PRs raised across projects. This delays PR reviews and merging. Moving to Github actions will run the CI independently.

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

### PR DESCRIPTION
**Pull request by anvithks**
**What type of PR is this?**
/kind enhancement

**What this PR does / why we need it**:
This PR adds the 
**Which issue(s) this PR fixes**:

Fixes #1314 

**Test Report Added?**:
 /kind TESTED

**Test Report**:
The workflow run status can be seen in the Actions Tab.

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by asifdxtreme — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Comment by skdwriting** [comment]
CI migration in progerss to github actions, local ci ok. hence merging.

**Pull request merged**
