### PR TITLE
[WIP] Writing test cases for volume group feature in pkg/controller

### PR DESCRIPTION
**Pull request by nguptaopensds**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
/kind enhancement

**What this PR does / why we need it**:
This PR is to automate and add more test cases to increase coverage in api/pkg/controller 

**Which issue(s) this PR fixes**:
This is a child PR for issue #1270 

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
 /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by nguptaopensds** [comment]
The test cases are not finished yet, testing report will add in some time

**Comment by kumarashit** [comment]
@nguptaopensds any update on this PR? What is the issue?

**Comment by kumarashit** [comment]
issues while running tests is one thing..Were you code ever built?

**Comment by nguptaopensds** [comment]
Closing this PR , opened another #1300

**Pull request closed without merging**
